[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --limit-max-requests 104857600 --timeout-keep-alive 300"

[variables]
NGINX_CLIENT_MAX_BODY_SIZE = "100M"
